version: 0.4


phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing npm......
      - npm install

  pre_build:
    commands:
      - echo installing dependencies...
      - npm

  build:
    commands:
      - echo building...
      - npm build

artifacts:
  files:
    - "**/*"

  discard-paths: no
  base-directory: dist
