version: 0.2


phases:
  install:
    runtime-versions:
      nodejs: 14

    commands:
        - n 16

  pre_build:
    commands:
      - echo installing dependencies...
      - npm

  build:
    commands:
      - echo building...
      - npm build

artifacts:
  files:
    - "**/*"

  discard-paths: no
  base-directory: dist
