version: 0.2


phases:
  install:
    commands:
      - echo installing Node 16...
      - curl -fsSL https://deb.nodesource.com/setup_16.x | -E bash - &&\
      - apt install -y nodejs
      - echo Installing npm......
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      - . ~/.nvm/nvm.sh
      - nvm install --lts
      - node -e "console.log('Running Node.js ' + process.version)"

  pre_build:
    commands:
      - echo installing dependencies...
      - npm

  build:
    commands:
      - echo building...
      - npm build

artifacts:
  files:
    - "**/*"

  discard-paths: no
  base-directory: dist
